[build]
  command = "npm run build"
  publish = "dist/arthemis"  # Ajusta esto según tu configuración
  functions = "dist/functions"  # Ajusta esto según tu configuración

[dev]
  command = "npm run dev"

[[redirects]]
  from= "/*"
  to = "/index.html"
  status=200